/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2023-02-17 06:29:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1661240047570L));
    _jspx_dependants.put("jar:file:/C:/yjy0217_mission2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/test2/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"utf-8\">\n");
      out.write("	<link\n");
      out.write("			href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\n");
      out.write("			rel=\"stylesheet\"\n");
      out.write("			integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\n");
      out.write("			crossorigin=\"anonymous\">\n");
      out.write("	<script\n");
      out.write("			src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("			integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\"\n");
      out.write("			crossorigin=\"anonymous\">\n");
      out.write("	</script>\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.3.min.js\"></script>\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/exceljs/4.3.0/exceljs.min.js\"></script>\n");
      out.write("	<script lang=\"javascript\" src=\"https://cdn.sheetjs.com/xlsx-0.19.2/package/dist/xlsx.full.min.js\"></script>\n");
      out.write("\n");
      out.write("<title>야호</title>\n");
      out.write("\n");
      out.write("	<style>\n");
      out.write("		.pop {\n");
      out.write("			display: none;\n");
      out.write("			position: fixed;\n");
      out.write("			top: 0;\n");
      out.write("			left: 0;\n");
      out.write("			z-index: 100;\n");
      out.write("			width: 100%;\n");
      out.write("			height: 100%;\n");
      out.write("			background: rgba(0, 0, 0, .5);\n");
      out.write("		}\n");
      out.write("		.pop.on{\n");
      out.write("			display: block;\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		.pop .info {\n");
      out.write("			overflow-y: auto;\n");
      out.write("			position: absolute;\n");
      out.write("			top: 50%;\n");
      out.write("			left: 50%;\n");
      out.write("			transform: translate(-50%, -50%);\n");
      out.write("			width: 800px;\n");
      out.write("			height: 330px;\n");
      out.write("			max-height: 92%;\n");
      out.write("			margin: 0 auto;\n");
      out.write("			background: #fff;\n");
      out.write("			border-radius: 5px;\n");
      out.write("			padding: 10px;\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		.pop .info table {\n");
      out.write("			width: 100%;\n");
      out.write("			border: 1px solid #ddd;\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		.pop .info table tr th ,\n");
      out.write("		.pop .info table tr td {\n");
      out.write("			height: 50px;\n");
      out.write("			padding-left: 10px;\n");
      out.write("			vertical-align: middle;\n");
      out.write("			border: 1px solid #ddd;\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		.pop .info table tr td input[type=text] ,\n");
      out.write("		.pop .info table tr td select {\n");
      out.write("			width: 40%;\n");
      out.write("			height: 40px;\n");
      out.write("			padding: 0 15px;\n");
      out.write("			border: 1px solid #ddd;\n");
      out.write("			border-radius: 3px;\n");
      out.write("			outline: none;\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		.pop .info .bottom {\n");
      out.write("\n");
      out.write("		}\n");
      out.write("		.pop .info .bottom .button_area {\n");
      out.write("			text-align: center;\n");
      out.write("			margin-top: 10px;\n");
      out.write("		}\n");
      out.write("\n");
      out.write("	</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<h2></h2>\n");
      out.write("\n");
      out.write("	<div class=\"container\" style= \"margin-top: 80px\">\n");
      out.write("		<div>\n");
      out.write("			<input type=\"text\" id=\"memberId\" placeholder=\"아이디\" class=\"form-control\" onfocusout=\"fn_dupCheck(this)\" \n");
      out.write("			value=\"\" style= \"width: 200px; margin-bottom:10px\"/>\n");
      out.write("			<input type=\"text\" id=\"memberNm\" placeholder=\"이름\" class=\"form-control\"\n");
      out.write("			style= \"width: 200px; margin-bottom:10px\"/>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"daterange\" style= \"margin-top: 25px\">\n");
      out.write("			<input type=\"date\" name=\"startDate\" id=\"startDate\" />\n");
      out.write("			<input type=\"date\" name=\"endDate\" id=\"endDate\" />\n");
      out.write("		</div>\n");
      out.write("		<div class=\"sex\" style= \"margin-top:10px; margin-bottom:10px;\">\n");
      out.write("			<input type=\"radio\" name=\"sex\" id=\"sexM\" value=\"male\" onchange=\"fn_list()\"  />\n");
      out.write("			<label for=\"sexM\">남성</label>\n");
      out.write("			<input type=\"radio\" name=\"sex\" id=\"sexF\" value=\"female\" onchange=\"fn_list()\" />\n");
      out.write("			<label for=\"sexF\">여성</label>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<select name=\"country\" id=\"country\" onchange=\"Change(this,'city')\">\n");
      out.write("			<option value=\"none\" selected>국가</option>\n");
      out.write("			<option value=\"한국\">한국</option>\n");
      out.write("			<option value=\"미국\">미국</option>\n");
      out.write("			<option value=\"중국\">중국</option>\n");
      out.write("			<option value=\"일본\">일본</option>\n");
      out.write("		</select> \n");
      out.write("		<select id=\"city\">\n");
      out.write("			<option value=\"none\" selected>도시</option>\n");
      out.write("		</select>\n");
      out.write("		<br>\n");
      out.write("		<div class=\"button\" style= \"margin-top:10px; border-radius: 20px;\">\n");
      out.write("			<button class=\"registerButton clickedButton\" onclick=\"fn_addRow(this)\" style= \"border-radius: 10px;\">\n");
      out.write("				<span>추가하기</span> <i class=\"zmdi zmdi-arrow-right\"></i>\n");
      out.write("			</button>\n");
      out.write("			<button class=\"registerButton clickedButton\" onclick=\"fn_save('s')\" style= \"border-radius: 10px;\">\n");
      out.write("				<span>저장하기</span> <i class=\"zmdi zmdi-arrow-right\"></i>\n");
      out.write("			</button>\n");
      out.write("			<button class=\"searchButton clickedButton\" onclick=\"fn_list()\" style= \"border-radius: 10px;\">\n");
      out.write("				<span>조회하기</span> <i class=\"zmdi zmdi-arrow-right\"></i>\n");
      out.write("			</button>\n");
      out.write("			<button class=\"excelButton clickedButton\" onclick=\"fn_excel()\" style= \"border-radius: 10px;\">\n");
      out.write("				<span>엑셀다운</span> <i class=\"zmdi zmdi-arrow-right\"></i>\n");
      out.write("			</button>\n");
      out.write("			<button class=\"deleteButton\" onclick=\"fn_delete()\" style= \"border-radius: 10px;\">\n");
      out.write("				<span>삭제하기</span> <i class=\"zmdi zmdi-arrow-right\"></i>\n");
      out.write("			</button>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"list\" style= \"margin: 50px 80px 50px 50px;\" >\n");
      out.write("	<table class=\"table table-striped\" style= \"border: 3px;\">\n");
      out.write("		<thead>\n");
      out.write("			<tr>\n");
      out.write("				<th scope=\"col\">\n");
      out.write("					<input type=\"checkbox\" id=\"allCheck\" onchange=\"fn_allCheck(this)\" />\n");
      out.write("					<label for=\"allCheck\">선택</label>\n");
      out.write("				</th>\n");
      out.write("				<th scope=\"col\">아이디</th>\n");
      out.write("				<th scope=\"col\">이름</th>\n");
      out.write("				<th scope=\"col\">성별</th>\n");
      out.write("				<th scope=\"col\">국가</th>\n");
      out.write("				<th scope=\"col\">도시</th>\n");
      out.write("			</tr>\n");
      out.write("		</thead>\n");
      out.write("		<tbody id=\"data_tbody\">\n");
      out.write("\n");
      out.write("		</tbody>\n");
      out.write("	</table>\n");
      out.write("<input type=\"hidden\" id=\"modifyId\" />\n");
      out.write("</div>\n");
      out.write("<div class=\"pop\">\n");
      out.write("	<div class=\"info\">\n");
      out.write("\n");
      out.write("		<table>\n");
      out.write("			<colgroup>\n");
      out.write("				<col style=\"width: 20%;\">\n");
      out.write("				<col style=\"width: 80%;\">\n");
      out.write("			</colgroup>\n");
      out.write("			<tbody>\n");
      out.write("			<tr>\n");
      out.write("				<th>아이디</th>\n");
      out.write("				<td><input type=\"text\" id=\"mMemberId\" onfocusout=\"fn_dupCheck(this)\" /></td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<th>이름</th>\n");
      out.write("				<td><input type=\"text\" id=\"mMemberNm\" /></td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<th>성별</th>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"radio\" name=\"mSex\" id=\"mMale\" value=\"male\" />\n");
      out.write("					<label for=\"mMale\">남</label>\n");
      out.write("					<input type=\"radio\" name=\"mSex\" id=\"mFemale\" value=\"female\" />\n");
      out.write("					<label for=\"mFemale\">여</label>\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<th>국가</th>\n");
      out.write("				<td>\n");
      out.write("					<select id=\"mCountry\" onchange=\"Change(this,`mCity`)\">\n");
      out.write("						<option value=\"none\" selected>국가</option>\n");
      out.write("						<option value=\"한국\">한국</option>\n");
      out.write("						<option value=\"미국\">미국</option>\n");
      out.write("						<option value=\"중국\">중국</option>\n");
      out.write("						<option value=\"일본\">일본</option>\n");
      out.write("					</select>\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<th>도시</th>\n");
      out.write("				<td>\n");
      out.write("					<select id=\"mCity\"></select>\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			</tbody>\n");
      out.write("		</table>\n");
      out.write("\n");
      out.write("		<div class=\"bottom\">\n");
      out.write("			<div class=\"button_area\">\n");
      out.write("				<button type=\"button\" onclick=\"fn_save('m')\">저장</button>\n");
      out.write("				<button type=\"button\" onclick=\"fn_hide()\">닫기</button>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(function () {\n");
      out.write("\n");
      out.write("})\n");
      out.write("\n");
      out.write("var fn_dupCheck = function (tag) {\n");
      out.write("	\n");
      out.write("	if($(tag).val() != \"\") {\n");
      out.write("		$.ajax({\n");
      out.write("	        url	:'/member/dupCheck.json',\n");
      out.write("	        type:'POST',\n");
      out.write("	        data:{memberId:$(tag).val()},\n");
      out.write("	        success: function(res) {\n");
      out.write("				if(res > 0) {\n");
      out.write("					return alert(\"아이디가 중복됩니다.\");\n");
      out.write("				}\n");
      out.write("\n");
      out.write("	        }\n");
      out.write("	    });		\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("}\n");
      out.write("\n");
      out.write("var fn_hide = function () {\n");
      out.write("	$('.pop.on').removeClass('on');\n");
      out.write("}\n");
      out.write("\n");
      out.write("var fn_addRow = function () {\n");
      out.write("\n");
      out.write("    if($('#sMemberId').length > 0) {\n");
      out.write("        return alert('아직 작업중인 row 가 있습니다.\\n작업 완료 후 추가하세요.');\n");
      out.write("    }\n");
      out.write("\n");
      out.write("	var addTr = '<tr>';\n");
      out.write("    addTr += '<td></td>';\n");
      out.write("    addTr += '<td><input id=\"sMemberId\" onfocusout=\"fn_dupCheck(this)\" /></td>';\n");
      out.write("    addTr += '<td><input id=\"sMemberNm\" /></td>';\n");
      out.write("    addTr += '<td>';\n");
      out.write("    addTr += '  <input type=\"radio\" name=\"sSex\" id=\"sMale\" value=\"male\" checked/><label for=\"sMale\">남</label>';\n");
      out.write("    addTr += '  <input type=\"radio\" name=\"sSex\" id=\"sFemale\" value=\"female\"/><label for=\"sFemale\">여</label>';\n");
      out.write("    addTr += '</td>';\n");
      out.write("    addTr += '<td>';\n");
      out.write("    addTr += '  <select name=\"country\" id=\"sCountry\" onchange=\"Change(this,`sCity`)\">';\n");
      out.write("    addTr += '      <option value=\"none\" selected>국가</option>';\n");
      out.write("    addTr += '      <option value=\"한국\">한국</option>';\n");
      out.write("    addTr += '      <option value=\"미국\">미국</option>';\n");
      out.write("    addTr += '      <option value=\"중국\">중국</option>';\n");
      out.write("    addTr += '      <option value=\"일본\">일본</option>';\n");
      out.write("    addTr += '  </select>';\n");
      out.write("    addTr += '</td>';\n");
      out.write("    addTr += '<td>';\n");
      out.write("    addTr += '  <select id=\"sCity\">';\n");
      out.write("    addTr += '      <option value=\"none\" selected>도시</option>';\n");
      out.write("    addTr += '  </select>';\n");
      out.write("    addTr += '</td>';\n");
      out.write("    addTr += '</tr>';\n");
      out.write("    $('#data_tbody').prepend(addTr);\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("// 초기화\n");
      out.write("var fn_reset = function () {\n");
      out.write("\n");
      out.write("    $('#memberId , #memberNm , #modifyId').val('');\n");
      out.write("\n");
      out.write("    // 날짜 오늘날짜로 셋팅\n");
      out.write("    var date = new Date();\n");
      out.write("    var month = date.getMonth().toString().length===1 ? '0'+(date.getMonth()+1) : date.getMonth();\n");
      out.write("    $('input[type=date]').val(date.getFullYear() +'-'+ month + '-' + date.getDate());\n");
      out.write("\n");
      out.write("    $('#sexM').prop('checked',true);\n");
      out.write("\n");
      out.write("    $('#country').val('none');\n");
      out.write("	$('#city').empty().append('<option value=\"none\" selected>도시</option>');\n");
      out.write("}\n");
      out.write("\n");
      out.write("// 목록\n");
      out.write("var fn_list = function () {\n");
      out.write("    var param = {};\n");
      out.write("    param.memberId  = $('#memberId').val();\n");
      out.write("    param.memberNm  = $('#memberNm').val();\n");
      out.write("    param.startDate = $('#startDate').val().replaceAll('-','');\n");
      out.write("    param.endDate   = $('#endDate').val().replaceAll('-','');\n");
      out.write("    param.sex       = $('input[name=sex]:checked').val();\n");
      out.write("    param.country   = $('#country').val();\n");
      out.write("    param.city      = $('#city').val();\n");
      out.write("\n");
      out.write("    $.ajax({\n");
      out.write("        url	:'/member/list.json',\n");
      out.write("        type:'POST',\n");
      out.write("        data:param,\n");
      out.write("        success: function(res) {\n");
      out.write("\n");
      out.write("            $('#data_tbody').empty();\n");
      out.write("\n");
      out.write("            for(var data of res) {\n");
      out.write("                var html = '<tr>';\n");
      out.write("                html += '<td><input data-id=\"'+data.memberId+'\" type=\"checkbox\"></td>';\n");
      out.write("                html += '<td ondblclick=\"fn_detail(`'+data.memberId+'`)\">'+data.memberId+'</td>';\n");
      out.write("                html += '<td>'+data.memberNm+'</td>';\n");
      out.write("                html += '<td>'+data.sex+'</td>';\n");
      out.write("                html += '<td>'+data.country+'</td>';\n");
      out.write("                html += '<td>'+data.city+'</td>';\n");
      out.write("                html += '</tr>';\n");
      out.write("                $('#data_tbody').append(html);\n");
      out.write("            }\n");
      out.write("\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("}\n");
      out.write("\n");
      out.write("// 상세\n");
      out.write("var fn_detail = function (memberId) {\n");
      out.write("    $('.pop').addClass('on');\n");
      out.write("    $('#modifyId').val(memberId);\n");
      out.write("\n");
      out.write("    $.ajax({\n");
      out.write("        url	:'/member/detail.json',\n");
      out.write("        type:'POST',\n");
      out.write("        data:{memberId : memberId},\n");
      out.write("	    success: function(res) {\n");
      out.write("\n");
      out.write("            $('#mMemberId').val(res.memberId);\n");
      out.write("            $('#mMemberNm').val(res.memberNm);\n");
      out.write("\n");
      out.write("            res.sex === 'male' ? $('#mMale').prop('checked',true) : $('#mFemale').prop('checked',true);\n");
      out.write("\n");
      out.write("            $('#mCountry').val(res.country).trigger('change');\n");
      out.write("            $('#mCity').val(res.city);\n");
      out.write("\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("}\n");
      out.write("\n");
      out.write("// 저장\n");
      out.write("var fn_save = function (flag) {\n");
      out.write("\n");
      out.write("	var param = {};\n");
      out.write("	param.memberId  = $('#'+flag+'MemberId').val();\n");
      out.write("	param.memberNm  = $('#'+flag+'MemberNm').val();\n");
      out.write("    param.country   = $('#'+flag+'Country').val();\n");
      out.write("    param.city      = $('#'+flag+'City').val();\n");
      out.write("\n");
      out.write("    var url = 'insert.json';\n");
      out.write("	if(flag === 'm') {\n");
      out.write("        param.sex       = $('input[name=mSex]:checked').val();\n");
      out.write("        param.modifyId  = $('#modifyId').val();\n");
      out.write("        url             = 'update.json';\n");
      out.write("	} else {\n");
      out.write("        if($('#sMemberId').length < 1) {\n");
      out.write("            return alert('[추가]버튼 클릭 후 작업하세요.');\n");
      out.write("        }\n");
      out.write("        param.sex       = $('input[name=sSex]:checked').val();\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	if(param.memberId === '') {\n");
      out.write("	    return alert('아이디를 입력해주세요.');\n");
      out.write("	}\n");
      out.write("	if(param.memberNm === '') {\n");
      out.write("	    return alert('이름을 입력해주세요.');\n");
      out.write("	}\n");
      out.write("	if(param.country === 'none') {\n");
      out.write("	    return alert('국가를 선택해주세요.');\n");
      out.write("	}\n");
      out.write("	if(param.city === 'none') {\n");
      out.write("	    return alert('도시를 선택해주세요.');\n");
      out.write("	}\n");
      out.write("\n");
      out.write("    $.ajax({\n");
      out.write("        url	:'/member/'+url,\n");
      out.write("        type:'POST',\n");
      out.write("        data:param,\n");
      out.write("	    success: function(res) {\n");
      out.write("	        if(res === 1) {\n");
      out.write("                fn_list();\n");
      out.write("                if(flag === 'm') {\n");
      out.write("                    fn_hide()\n");
      out.write("                }\n");
      out.write("	            return alert('저장되었습니다.');\n");
      out.write("	        }\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("}\n");
      out.write("\n");
      out.write("// 삭제\n");
      out.write("var fn_delete = function () {\n");
      out.write("\n");
      out.write("    var param = {} , memberIdArr = [];\n");
      out.write("\n");
      out.write("    if($('#data_tbody input[type=checkbox]:checked').length < 1) {\n");
      out.write("        return alert('삭제 할 데이터를 선택해주세요.');\n");
      out.write("    }\n");
      out.write("    $('#data_tbody input[type=checkbox]:checked').each(function(i,t) {\n");
      out.write("        memberIdArr.push($(t).data('id'));\n");
      out.write("    })\n");
      out.write("    param.memberIdArr = memberIdArr;\n");
      out.write("\n");
      out.write("    $.ajax({\n");
      out.write("        url	:'/member/delete.json',\n");
      out.write("        type:'POST',\n");
      out.write("        data:JSON.stringify(param),\n");
      out.write("        contentType : 'application/json',\n");
      out.write("	    success: function(res) {\n");
      out.write("            if(res > 0) {\n");
      out.write("                fn_list();\n");
      out.write("                return alert('삭제 되었습니다.');\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("// 전체선택\n");
      out.write("var fn_allCheck = function (tag) {\n");
      out.write("	if($(tag).is(':checked')) {\n");
      out.write("        $('#data_tbody input[type=checkbox]').prop('checked',true);\n");
      out.write("	} else {\n");
      out.write("        $('#data_tbody input[type=checkbox]').prop('checked',false);\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("// 엑셀\n");
      out.write("var fn_excel = function () {\n");
      out.write("    var wb = XLSX.utils.table_to_book(document.getElementById('data_tbody'), {sheet:\"시트명\",raw:true});\n");
      out.write("    XLSX.writeFile(wb, ('파일명.xlsx'));\n");
      out.write("}\n");
      out.write("\n");
      out.write("var Change = function (tag , target) {\n");
      out.write("	var city_z = [ \"none\" ];\n");
      out.write("	var city_a = [ \"서울\", \"부산\", \"창원\", \"경주\",\"대구\",\"대전\", \"통영\" ];\n");
      out.write("	var city_b = [ \"NYC\", \"LA\", \"Pheonix\", \"Tucson\", \"Litiz\", \"Lafayette\" ];\n");
      out.write("	var city_c = [ \"베이징\", \"상하이\", \"광저우\", \"청두\", \"우한\", \"톈진\" ];\n");
      out.write("	var city_d = [ \"도쿄\", \"오사카\", \"삿포로\", \"교토\", \"후쿠오카\", \"고베\" ];\n");
      out.write("\n");
      out.write("	var targetTag = document.getElementById(target);\n");
      out.write("\n");
      out.write("	var d = '';\n");
      out.write("	switch (tag.value) {\n");
      out.write("		case '한국': d = city_a; break;\n");
      out.write("		case '미국': d = city_b; break;\n");
      out.write("		case '중국': d = city_c; break;\n");
      out.write("		case '일본': d = city_d; break;\n");
      out.write("		default:  d = city_z;\n");
      out.write("    }\n");
      out.write("    targetTag.options.length = 0;\n");
      out.write("\n");
      out.write("	for (var x in d) {\n");
      out.write("		var opt = document.createElement(\"option\");\n");
      out.write("		opt.value = d[x];\n");
      out.write("        opt.innerHTML = d.length > 1 ? d[x] : '도시';\n");
      out.write("        targetTag.appendChild(opt);\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
